version: '3.8'

services:
  
  # Service 1: Our Transaction Web Gateway Backend
  transaction-api:
    build: .
    container_name: production-gateway-app
    ports:
      - "9090:80"
    volumes:
      - ./container-logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  # Service 2: The Core Banking Cache (Simulating a Multi-Container Dependency)
  banking-cache:
    image: redis:7-alpine
    container_name: cluster-redis-cache
