services:
  transaction-api:
    build: .
    container_name: production-gateway-app
    ports:
      - "9090:80"
    volumes:
      - ./container-logs:/app/logs
    # Inject variables dynamically from outside the application code box
    environment:
      - JPMC_PORT=80
      - JPMC_ENV=STAGING_ENVIRONMENT
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  banking-cache:
    image: redis:7-alpine
    container_name: cluster-redis-cache
